[package]
name = "suter_proofs"
version = "0.1.0"
authors = ["YI <uuuuuu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elgamal_ristretto = { git = "https://github.com/iquerejeta/elgamal.git" }
curve25519-dalek = "2.0.0"
quickcheck = "0.9.0"
rand = "0.7.2"
rand_core = "0.5.1"
quickcheck_macros = "0.8.0"
